[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/gabriel-vasile/mimetype"
  version = "0.3.7"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.3.0"
